"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { LogOut, Users, BookOpen, Star, RefreshCw, Copy, Check, Video, VideoOff, X, MessageSquare, Play } from "lucide-react";
import { useRouter } from "next/navigation";
import { loadData, removeData, saveData } from "@/lib/db";
import toast from "react-hot-toast";

export default function TeacherDashboard() {
  const router = useRouter();
  const [profile, setProfile] = useState<any>(null);
  const [classCode, setClassCode] = useState<string>("");
  const [students, setStudents] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [isLive, setIsLive] = useState(false);
  const [chatStudent, setChatStudent] = useState<any | null>(null);
  const [directMessages, setDirectMessages] = useState<any[]>([]);
  const [messageInput, setMessageInput] = useState("");

  useEffect(() => {
    const init = async () => {
      const p = await loadData("edu_profile");
      if (!p || p.role !== "teacher") {
        router.push("/dashboard"); // Redirect to student dashboard if not teacher
        return;
      }
      setProfile(p);
      
      let code = await loadData("edu_class_code");
      if (!code) {
        code = Math.random().toString(36).substring(2, 8).toUpperCase();
        await saveData("edu_class_code", code);
      }
      setClassCode(code);
      fetchStudents(code);

      // Check current live status
      const { db } = await import("@/lib/firebase");
      if (db) {
        const { doc, getDoc } = await import("firebase/firestore");
        const userId = localStorage.getItem("edu_user_id");
        if (userId) {
          const docSnap = await getDoc(doc(db, "users", userId));
          if (docSnap.exists() && docSnap.data().isLive) {
            setIsLive(true);
          }
        }
      }
    };
    init();
  }, [router]);

  // Listen for direct messages when a chat is open
  useEffect(() => {
    if (!chatStudent) return;
    
    let unsubscribe: any;
    const fetchMessages = async () => {
      try {
        const { db } = await import("@/lib/firebase");
        if (db) {
          const { collection, query, where, onSnapshot } = await import("firebase/firestore");
          const myId = localStorage.getItem("edu_user_id");
          
          const q = query(
            collection(db, "direct_messages"),
            where("teacherId", "==", myId),
            where("studentId", "==", chatStudent.id)
          );
          
          unsubscribe = onSnapshot(q, (snapshot) => {
            const msgs: any[] = [];
            snapshot.forEach(doc => msgs.push({ id: doc.id, ...doc.data() }));
            // Sort locally by timestamp
            msgs.sort((a, b) => (a.timestamp?.toMillis() || 0) - (b.timestamp?.toMillis() || 0));
            setDirectMessages(msgs);
          });
        }
      } catch (e) {
        console.error("Failed to fetch messages", e);
      }
    };
    fetchMessages();
    return () => { if (unsubscribe) unsubscribe(); };
  }, [chatStudent]);

  const sendDirectMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!messageInput.trim() || !chatStudent) return;
    
    try {
      const { db } = await import("@/lib/firebase");
      if (db) {
        const { collection, addDoc, serverTimestamp } = await import("firebase/firestore");
        const myId = localStorage.getItem("edu_user_id");
        
        await addDoc(collection(db, "direct_messages"), {
          teacherId: myId,
          studentId: chatStudent.id,
          senderId: myId,
          text: messageInput.trim(),
          timestamp: serverTimestamp()
        });
        setMessageInput("");
      }
    } catch (e) {
      console.error(e);
      toast.error("Failed to send message");
    }
  };

  const fetchStudents = async (code: string) => {
    setIsLoading(true);
    try {
      const { db } = await import("@/lib/firebase");
      if (db) {
        const { collection, query, where, getDocs } = await import("firebase/firestore");
        const q = query(collection(db, "users"), where("classCode", "==", code));
        const querySnapshot = await getDocs(q);
        const st: any[] = [];
        querySnapshot.forEach((doc) => {
          st.push({ id: doc.id, ...doc.data() });
        });
        setStudents(st);
      }
    } catch (e) {
      console.error("Failed to fetch students", e);
    } finally {
      setIsLoading(false);
    }
  };

  const copyCode = () => {
    navigator.clipboard.writeText(classCode);
    setCopied(true);
    toast.success("Class code copied!");
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleLive = async () => {
    // Automatically generate a secure, unique meeting room link based on the class code
    const autoGeneratedLink = `https://meet.jit.si/${classCode}-edubridge-live`;

    const newLiveStatus = !isLive;
    setIsLive(newLiveStatus);
    try {
      const { db } = await import("@/lib/firebase");
      if (db) {
        const { doc, setDoc } = await import("firebase/firestore");
        const userId = localStorage.getItem("edu_user_id");
        if (userId) {
          await setDoc(doc(db, "users", userId), { 
            isLive: newLiveStatus, 
            meetingLink: newLiveStatus ? autoGeneratedLink : null 
          }, { merge: true });
        }
      }
      if (newLiveStatus) {
        toast.success("You are now live! Students can join instantly.");
        // Open the teacher's room for them automatically in a new tab
        window.open(autoGeneratedLink, "_blank");
      }
    } catch(e) {
      console.error(e);
      toast.error("Failed to update live status.");
    }
  };

  const handleLogout = async () => {
    if (confirm("Are you sure you want to log out?")) {
      await removeData("edu_profile");
      localStorage.removeItem("edu_auth_token");
      router.push("/login");
    }
  };

  if (!profile) return null;

  return (
    <div className="flex flex-col h-full bg-slate-900 overflow-y-auto">
      <header className="px-8 py-6 border-b border-slate-800 bg-slate-900 flex items-center justify-between sticky top-0 z-10">
        <div>
          <h1 className="text-2xl font-bold font-heading text-white">Teacher Dashboard</h1>
          <p className="text-slate-400">
            Welcome, {profile.name}! {profile.subject && <span className="text-blue-400 font-medium ml-2">({profile.subject})</span>}
          </p>
        </div>
        <div className="flex items-center space-x-6">
          <button 
            onClick={toggleLive} 
            className={`flex items-center px-4 py-2 rounded-xl text-sm font-bold transition-all shadow-lg ${isLive ? 'bg-red-500/10 text-red-500 border border-red-500/50 hover:bg-red-500/20' : 'bg-emerald-600 hover:bg-emerald-500 text-white'}`}
          >
            {isLive ? <VideoOff className="w-4 h-4 mr-2" /> : <Video className="w-4 h-4 mr-2" />}
            {isLive ? "End Live Class" : "Go Live"}
          </button>
          <button onClick={handleLogout} className="flex items-center text-slate-400 hover:text-red-400 transition-colors">
            <LogOut className="w-5 h-5 md:mr-2" />
            <span className="hidden md:inline text-sm font-medium">Log Out</span>
          </button>
        </div>
      </header>

      <div className="p-8 space-y-8 max-w-5xl mx-auto w-full">
        {/* Class Code Card */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-slate-800 border border-slate-700 p-8 rounded-3xl flex flex-col md:flex-row items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-white mb-2">Your Class Code</h2>
            <p className="text-slate-400 text-sm max-w-md">Share this code with your students. When they enter it in their dashboard settings, they will appear in your roster below.</p>
          </div>
          <div className="mt-6 md:mt-0 flex items-center space-x-4">
            <div className="bg-slate-900 px-6 py-4 rounded-xl border border-slate-700 text-3xl font-mono font-bold tracking-widest text-emerald-400 shadow-inner">
              {classCode}
            </div>
            <button onClick={copyCode} className="p-4 bg-blue-600 hover:bg-blue-500 transition-colors text-white rounded-xl shadow-lg">
              {copied ? <Check className="w-6 h-6" /> : <Copy className="w-6 h-6" />}
            </button>
          </div>
        </motion.div>

        {/* Student Roster */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl font-bold text-white flex items-center">
              <Users className="w-6 h-6 mr-3 text-blue-400" /> 
              Student Roster ({students.length})
            </h3>
            <button onClick={() => fetchStudents(classCode)} className="text-slate-400 hover:text-white flex items-center text-sm transition-colors">
              <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} /> Refresh
            </button>
          </div>

          {isLoading ? (
            <div className="bg-slate-800/50 border border-slate-700/50 p-12 rounded-3xl flex flex-col items-center justify-center text-slate-400">
              <RefreshCw className="w-8 h-8 animate-spin mb-4 text-blue-400" />
              <p>Loading students...</p>
            </div>
          ) : students.length === 0 ? (
            <div className="bg-slate-800/50 border border-slate-700/50 p-12 rounded-3xl flex flex-col items-center justify-center text-center">
              <Users className="w-16 h-16 text-slate-600 mb-4" />
              <h4 className="text-lg font-bold text-white mb-2">No students yet</h4>
              <p className="text-slate-400 max-w-sm">When your students enter your class code on their dashboard, their progress will appear here.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {students.map((student, i) => (
                <div key={i} className="bg-slate-800 border border-slate-700 p-6 rounded-2xl shadow-lg relative overflow-hidden">
                  <div className="absolute -top-6 -right-6 w-24 h-24 bg-blue-500/10 rounded-full blur-xl pointer-events-none" />
                  
                  <div className="flex items-center space-x-4 mb-4">
                    <div className="w-12 h-12 bg-slate-700 rounded-full flex items-center justify-center font-bold text-xl text-white">
                      {student.name.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <h4 className="font-bold text-white text-lg">{student.name}</h4>
                      <p className="text-sm text-slate-400">{student.standard}</p>
                    </div>
                  </div>
                  
                  <div className="space-y-3">
                    <div className="flex items-center text-sm text-slate-300">
                      <BookOpen className="w-4 h-4 mr-2 text-purple-400" /> {student.subject}
                    </div>
                    <div className="flex items-center text-sm text-slate-300">
                      <Star className="w-4 h-4 mr-2 text-yellow-400" /> {student.xp || 0} XP
                    </div>
                  </div>
                  
                  <button 
                    onClick={() => setChatStudent(student)}
                    className="w-full mt-6 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-bold transition-all shadow-lg flex items-center justify-center text-sm"
                  >
                    <MessageSquare className="w-4 h-4 mr-2" /> Message Student
                  </button>
                </div>
              ))}
            </div>
          )}
        </motion.div>
      </div>

    </div>
    
      {/* Direct Messaging Panel */}
      <AnimatePresence>
        {chatStudent && (
          <motion.div 
            initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 25, stiffness: 200 }}
            className="fixed inset-y-0 right-0 z-50 w-full md:w-96 bg-slate-900 border-l border-slate-800 shadow-2xl flex flex-col"
          >
            <div className="p-6 border-b border-slate-800 flex items-center justify-between bg-slate-800/50">
              <div className="flex items-center">
                <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center font-bold text-white mr-3">
                  {chatStudent.name?.charAt(0).toUpperCase()}
                </div>
                <div>
                  <h3 className="font-bold text-white">{chatStudent.name}</h3>
                  <p className="text-xs text-slate-400">Direct Message</p>
                </div>
              </div>
              <button onClick={() => setChatStudent(null)} className="p-2 text-slate-400 hover:bg-slate-700 hover:text-white rounded-full transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              {directMessages.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-center opacity-50">
                  <MessageSquare className="w-12 h-12 text-slate-500 mb-4" />
                  <p className="text-slate-400 text-sm">Send a message to {chatStudent.name}.</p>
                </div>
              ) : (
                directMessages.map((msg, i) => {
                  const isMe = msg.senderId === localStorage.getItem("edu_user_id");
                  return (
                    <div key={i} className={`flex ${isMe ? 'justify-end' : 'justify-start'}`}>
                      <div className={`max-w-[80%] p-3 rounded-2xl ${isMe ? 'bg-blue-600 text-white rounded-br-sm' : 'bg-slate-800 border border-slate-700 text-slate-200 rounded-bl-sm'}`}>
                        <p className="text-sm break-words">{msg.text}</p>
                      </div>
                    </div>
                  );
                })
              )}
            </div>
            
            <div className="p-4 border-t border-slate-800 bg-slate-900">
              <form onSubmit={sendDirectMessage} className="flex space-x-2">
                <input 
                  type="text" 
                  value={messageInput}
                  onChange={e => setMessageInput(e.target.value)}
                  placeholder="Type a message..."
                  className="flex-1 bg-slate-800 border border-slate-700 rounded-xl px-4 py-3 focus:outline-none focus:border-blue-500 text-white text-sm transition-colors"
                />
                <button type="submit" disabled={!messageInput.trim()} className="bg-blue-600 hover:bg-blue-500 text-white p-3 rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed">
                  <Play className="w-5 h-5 fill-current" />
                </button>
              </form>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

  );
}
